//
// Created by huj25 on 11/8/2022.
//

#ifndef AK_IT_P_NS_ANTONSCVETKOVS_3MD_2UZD_PLAYERVSCPU_H
#define AK_IT_P_NS_ANTONSCVETKOVS_3MD_2UZD_PLAYERVSCPU_H


class PlayerVsCpu {

};


#endif //AK_IT_P_NS_ANTONSCVETKOVS_3MD_2UZD_PLAYERVSCPU_H
